### ISSUE TITLE
bootimage / bootloader config and update

### ISSUE THREAD

**Issue by Harry-R** [RWTH-OS/eduOS-rs#10]
When running `make qemu` on stage0 branch:

```
$ make qemu
bootimage build --target x86_64-eduos.json
Error: Failed to read bootimage configuration: unexpected `package.metadata.bootimage` key `bootloader` with value `name = "bootloader"
target = "x86_64-bootloader.json"
`
make: *** [Makefile:30: bootimage.bin] Error 1
```
So there seem to be some braking changes in config format.

When investigating the error, I found in the [doc](https://github.com/rust-osdev/bootimage), that:
`Note: At least bootloader version 0.5.1 is required since bootimage 0.7.0. For earlier bootloader versions, use bootimage 0.6.6`, but we use `bootloader = "0.3.4"`

Easy workaround would be to downgrade `bootimage` to 0.6.6 (I tested it and it works), but I think upgrading and fixing the config would be the better way.

**Comment by stlankes** [comment]
Oh, I dropped the support of bootloader.  Try `make run` to start the kernel. I don't longer use QEMU, I run the kernel in my own hypervisor _ehyve_.

**Comment by Harry-R** [comment]
Okay, than better remove `qemu` commands from Makefile and Cargo.toml to not confuse people?

**Comment by stlankes** [comment]
yes, it is obsolete
