### ISSUE TITLE
Use MacPorts as it ships with i386-elf binutils package

### ISSUE THREAD

**Issue by stv0g** [RWTH-OS/eduOS-rs#2]
Using macports has the advantage that we can skip the manual installation of binutils.

**Comment by stlankes** [comment]
Yeah, but I need x86_64-elf binutils. As far as I know, does MacPorts only support i386-elf.

**Comment by stv0g** [comment]
Ich glaube schon: 
https://www.macports.org/ports.php?by=name&substr=x86_64-elf-binutils

Damit hat es zumindestens bei mir gebaut.

Macports liefert auch ein rust-src Paket.
Aber das ist bestimmt kein Nightmare snapshot

**Comment by stlankes** [comment]
Hm, I have forgotten that MacPorts supports x86_64. I will extend the README with a description of MacPorts.

**Comment by stlankes** [comment]
I added a note in the README.
