### ISSUE TITLE
replace_boot_stack cannot work reliably, because all copies of RSP are not known

### ISSUE THREAD

**Issue by ColinFinck** [RWTH-OS/eduOS-rs#6]
replace_boot_stack adjusts the RSP register to point to the new stack and copies the contents of the old stack to the new stack.
However, adjusting the RSP register may not be enough. Other registers may also contain references to the old stack. Elements on the stack itself may even contain references to the old stack.

To give an example: Even though the "x86_64-unknown-none-gnu.json" file contains "eliminate-frame-pointer": true, this is just a possible optimization. The compiler may still decide to use RBP for memory references. Looking into the disassembly reveals that this indeed happens right in rust_main.
When entering replace_boot_stack, this RBP has been pushed somewhere on the stack, without any reliable way of adjusting this memory reference.

To solve this problem, I would keep using the original boot stack, and offer a way to pass the address of a dynamically allocated boot stack to the application processor boot code as soon as SMP is implemented.
In fact, this is how I will proceed for HermitCore-rs.

**Comment by stlankes** [comment]
Yes, you are right. The code is derived from a similar C code, where I am able to define that the compiler isn't able to use RBP. Your idea sounds code! Could you create a patch for eduOS?

**Comment by stlankes** [comment]
I remove completely the code...
